services:
  db:
    image: postgres:16-alpine
    container_name: mise-db
    environment:
      POSTGRES_USER: mise
      POSTGRES_PASSWORD: mise
      POSTGRES_DB: mise
    ports:
      - "5432:5432"
    volumes:
      - mise_pg:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mise -d mise"]
      interval: 3s
      timeout: 3s
      retries: 30


  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://mise:mise@db:5432/mise?schema=public
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    depends_on:
       db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env.docker
      
volumes:
  mise_pg:
